<script setup>
import { computed } from 'vue'
import { formatTzs } from '@/constants/trademarkRecordation'

const props = defineProps({
  modelValue: {
    type: Object,
    default: () => ({})
  },
  expectedAmount: {
    type: Number,
    default: 0
  },
  paymentRequired: {
    type: Boolean,
    default: true
  },
  controlNumberReadonly: {
    type: Boolean,
    default: false
  },
  readOnly: {
    type: Boolean,
    default: false
  }
})

const emit = defineEmits(['update:modelValue'])

const value = computed(() => ({
  status: props.modelValue?.status || 'pending_control_number',
  controlNumber: props.modelValue?.controlNumber || '',
  referenceNumber: props.modelValue?.referenceNumber || '',
  amountPaid: Number(props.modelValue?.amountPaid || 0),
  paidAt: props.modelValue?.paidAt || '',
  receiptNumber: props.modelValue?.receiptNumber || ''
}))

const outstandingAmount = computed(() =>
  Math.max(0, Number(props.expectedAmount || 0) - Number(value.value.amountPaid || 0))
)

function patch(field, nextValue) {
  emit('update:modelValue', {
    ...value.value,
    [field]: nextValue
  })
}
</script>

<template>
  <div class="space-y-4">
    <div class="grid grid-cols-1 gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 md:grid-cols-3">
      <article class="rounded-xl border border-slate-200 bg-white p-3">
        <p class="text-xs uppercase tracking-wide text-slate-500">Expected Fee</p>
        <p class="mt-1 text-lg font-semibold text-slate-900">{{ formatTzs(expectedAmount) }}</p>
      </article>
      <article class="rounded-xl border border-slate-200 bg-white p-3">
        <p class="text-xs uppercase tracking-wide text-slate-500">Amount Paid</p>
        <p class="mt-1 text-lg font-semibold text-emerald-700">{{ formatTzs(value.amountPaid) }}</p>
      </article>
      <article class="rounded-xl border border-slate-200 bg-white p-3">
        <p class="text-xs uppercase tracking-wide text-slate-500">Outstanding</p>
        <p class="mt-1 text-lg font-semibold text-amber-700">{{ formatTzs(outstandingAmount) }}</p>
      </article>
    </div>

    <el-alert
      v-if="!paymentRequired"
      title="This request type does not require statutory payment. You can continue with declaration and submission."
      type="success"
      :closable="false"
      show-icon
    />

    <div class="grid grid-cols-1 gap-3 md:grid-cols-2">
      <el-form-item class="mb-0" label="Payment Status">
        <el-select :model-value="value.status" :disabled="readOnly" @update:model-value="patch('status', $event)">
          <el-option label="Pending Control Number" value="pending_control_number" />
          <el-option label="Control Number Issued" value="control_number_issued" />
          <el-option label="Paid" value="paid" />
          <el-option label="Verified" value="verified" />
        </el-select>
      </el-form-item>

      <el-form-item class="mb-0" label="Control Number">
        <el-input
          :model-value="value.controlNumber"
          placeholder="Generated by finance"
          :readonly="controlNumberReadonly"
          @update:model-value="patch('controlNumber', $event)"
        />
      </el-form-item>

      <el-form-item class="mb-0" label="Payment Reference Number">
        <el-input
          :model-value="value.referenceNumber"
          placeholder="Bank / mobile money reference"
          :disabled="readOnly"
          @update:model-value="patch('referenceNumber', $event)"
        />
      </el-form-item>

      <el-form-item class="mb-0" label="Amount Paid (TZS)">
        <el-input-number
          :model-value="value.amountPaid"
          :min="0"
          controls-position="right"
          :disabled="readOnly"
          @update:model-value="patch('amountPaid', $event)"
        />
      </el-form-item>

      <el-form-item class="mb-0" label="Payment Date">
        <el-date-picker
          :model-value="value.paidAt"
          type="date"
          value-format="YYYY-MM-DD"
          :disabled="readOnly"
          @update:model-value="patch('paidAt', $event)"
        />
      </el-form-item>

      <el-form-item class="mb-0" label="Receipt Number">
        <el-input
          :model-value="value.receiptNumber"
          :disabled="readOnly"
          @update:model-value="patch('receiptNumber', $event)"
        />
      </el-form-item>
    </div>
  </div>
</template>
